name: TheShootCraft
main: com.gmail.sentrance1.TheShootCraft
version: 1.0-SNAPSHOT
author: Sentrance
description: TheShootCraft is a plugin trying to imitate in a MineCraft style the game ShootMania Storm. It is also my first Mini-Game so it may be not optimized in a lot of points.